### ISSUE TITLE
Fullscreen mode doesn't work

### ISSUE THREAD

**Issue by JoshCheek** [zenspider/graphics#24]
Given this code:

```ruby
require "graphics"
Graphics::Simulation.new(200, 200, 0, 'Example', true).run
```

It cannot find the constant `SDL::FULLSCREEN`

```
/Users/josh/.gem/ruby/2.3.1/gems/graphics-1.0.0b6/lib/graphics/simulation.rb:70:in `initialize': uninitialized constant SDL::FULLSCREEN (NameError)
Did you mean?  SDL::Screen
	from f4.rb:2:in `new'
	from f4.rb:2:in `<main>'
```

I looked through all the constants and didn't see it (grepped the otuput of this):

```ruby
%w[graphics graphics/body graphics/decorators graphics/extensions graphics/rainbows graphics/simulation graphics/trail graphics/v sdl/sdl]
  .each { |p| require p }

def all_consts(mod, seen)
  return mod unless mod.kind_of? Module
  return mod if seen.include? mod
  seen << mod
  mod.constants.map { |name|
    const = mod.const_get name
    [name, all_consts(const, seen)]
  }.to_h
end

require 'pp'
pp all_consts(SDL, [])
```

Looks like it was supposed to be defined [here](https://github.com/zenspider/graphics/blob/f8cb142072f31a4be4d54f2047a51e9ea39e7093/ext/sdl/sdl.c#L981)

**Comment by zenspider** [comment]
Just hadn't ported that constant forward in the rewrite. Fixed. Thanks!

**Comment by JoshCheek** [comment]
Tried this just now and it did go fullscreen, but just displayed a black screen that I couldn't figure out how to get out of. I could see my mouse, music and brightness controls worked, but the fancy zoom-out-of-my-app controls didn't, swiping left/right didn't work, command-tab didn't work, command-option-esc didn't work. I wound up having to hard-reset to get out of it.

**Comment by zenspider** [comment]
https://github.com/zenspider/graphics/blob/b9307a0e1b018cd0b236617926a8f688f4078a60/lib/graphics/simulation.rb#L98-L99

should work unless overridden

**Comment by JoshCheek** [comment]
I assume I pressed "esc", I'm hesitant to try again :P 

It might have been the difference between running w/ `rdsl` and `ruby`, eg when I run the logo example you pointed me at, nothing happens when I run it with `ruby`, but when I run it with `rsdl` it works fine.

This could also be a problem with my computer, I tried running Crystal's [SDL examples](https://github.com/crystal-lang/crystal/tree/b6e474474187dd004ea555febded5b5c162281e7/samples/sdl) and they were all blank screens with this error (note that I killed it w/ cmd+opt+esc, and that may have been the cause of some of it). I'm not expecting you to do anything with this, just figured it was easy enough to include and may have some useful info.

```
$ crystal fire.cr
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Warning>: Invalid Connection ID 0
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: CGSSetWindowTitle: Invalid window
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Warning>: Invalid Connection ID 0
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: CGSSetWindowTitle: Invalid window
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Warning>: Invalid Connection ID 0
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: CGSSetWindowTitle: Invalid window
2016-11-22 02:10:47.724 crystal-run-fire.tmp[55579:1106936] _initWithWindowNumber: error creating graphics ctxt object for ctxt:0x0, window:0x0
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: CGContextDrawImage: invalid context 0x0. Backtrace:
	  <SDL_UpdateRect+77>
	   <SDL_Flip+352>
	    <SDL_SetVideoMode+1225>
	     <*SDL::set_video_mode<Int32, Int32, Int32, UInt32>:SDL::Surface+37>
	      <__crystal_main+2072>
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: CGContextFlush: invalid context 0x0. Backtrace:
	  <SDL_UpdateRect+77>
	   <SDL_Flip+352>
	    <SDL_SetVideoMode+1225>
	     <*SDL::set_video_mode<Int32, Int32, Int32, UInt32>:SDL::Surface+37>
	      <__crystal_main+2072>
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: CGContextDrawImage: invalid context 0x0. Backtrace:
	  <SDL_UpdateRect+77>
	   <SDL_Flip+352>
	    <*SDL::Surface#flip:Int32+13>
	     <__crystal_main+7962>
Nov 22 02:10:47  crystal-run-fire.tmp[55579] <Error>: CGContextFlush: invalid context 0x0. Backtrace:
	  <SDL_UpdateRect+77>
	   <SDL_Flip+352>
	    <*SDL::Surface#flip:Int32+13>
	     <__crystal_main+7962>
Nov 22 02:10:47  crystal-run1039 frames in 2810 ms
Average FPS: 369.75088967971527
```
